### ISSUE TITLE
UpdateLocation

### ISSUE THREAD

**Issue by sjohandup** [Broadsword-GIS-Org/SE_BroadSword-GIS#13]
Create a method that can update an existing location by possibly accepting oldVenueName, oldCoordinates, newVenueName and newCoordinates.  Then updating the database accordingly.

**Comment by BernhardSchuld** [comment]
We may need to expand on just the base function. Possibly updateByX, where X is ID, name, etc.
Not critical to functioning API, but would be helpful.

**Comment by sjohandup** [comment]
Basic update feature implemented, but will need updating due to changes made to the json structure.

**Comment by sjohandup** [comment]
update method was amended according the latest location structure.  by @hjvandermerwe
