### ISSUE TITLE
DeleteLocation

### ISSUE THREAD

**Issue by sjohandup** [Broadsword-GIS-Org/SE_BroadSword-GIS#14]
Create a method that accepts location information, then removes it from the database.

**Comment by BernhardSchuld** [comment]
We may need to expand on just the base function. Possibly deleteByX, where X is ID, name, etc

**Comment by sjohandup** [comment]
Basic delete feature implemented, but will need updating due to changes made to the json structure.

**Comment by sjohandup** [comment]
Delete method was amended accordingly by @hjvandermerwe
