### ISSUE TITLE
Implement A* library for route calculation

### ISSUE THREAD

**Issue by BernhardSchuld** [Broadsword-GIS-Org/SE_BroadSword-GIS#28]
The Navigation team are not allowed to cache our entire map. Therefore we have to return the calculated routes between two given points. There is a node-astar npm package.

**Comment by sjohandup** [comment]
@BernhardSchuld was able to succesfully implement a node-astar algorithm for us to calculate a route between locationA. and locationB via their location ids.  The method then returns an array of locations starting from locationA and ending at locationB.
