### ISSUE TITLE
Unit Tests / Integration Tests

### ISSUE THREAD

**Issue by BernhardSchuld** [Broadsword-GIS-Org/SE_BroadSword-GIS#29]
Need to have done before final demo. The earlier the better as it helps the development process

**Comment by sjohandup** [comment]
I was able to continue the unit tests @BernhardSchuld started working on.  
I created passing unit tests for:
- CREATE
- READ
- UPDATE
- DELETE
- getByBuildingName
- getBuildingNames
- getById
- getRoute
