### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by BernhardSchuld** [Broadsword-GIS-Org/SE_BroadSword-GIS#33]
We need to validate that all fields are correctly entered and not empty with creation.

**Comment by Tlaka95** [comment]
@KamoKG  Are you doing both this and number #32 ?

**Comment by KamoKG** [comment]
@Tlaka95 I've started with the validation, should be done by tomorrow.. you want to handle #32?

**Comment by sjohandup** [comment]
validation completed
