### ISSUE TITLE
Automatically Populate DB

### ISSUE THREAD

**Issue by BernhardSchuld** [Broadsword-GIS-Org/SE_BroadSword-GIS#35]
We need to find a way to populate our DB with campus locations from a file (JSON for now, actual GIS files later). 
It is important to have this happen automatically when we start our server (without creating duplicates).

NOTE: This should be done after #34 is completed. Though, if you can do this issue, it will automatically solve issue #34.

**Comment by sjohandup** [comment]
@Tlaka95 managed to create a seed that we can use to populate our mongo database with location data collected by @hjvandermerwe
