### ISSUE TITLE
getBuildingNames

### ISSUE THREAD

**Issue by BernhardSchuld** [Broadsword-GIS-Org/SE_BroadSword-GIS#36]
Need to create this function so that Access can display a list of buildings.

**Comment by KamoKG** [comment]
I can do that..

**Comment by BernhardSchuld** [comment]
@KamoKG Cool. Have a look at the "distinct" feature of mongo querying and just apply that to the mongoose way of querying.

**Comment by BernhardSchuld** [comment]
And remember to assign yourself :)

**Comment by sjohandup** [comment]
@KamoKG was able to successfully implement the getBuildingNames method which can be called via NSQ by other modules and will receive a JSON array of the available buildings only if we have existing locations at that building.
