### ISSUE TITLE
getVenuesByBuilding

### ISSUE THREAD

**Issue by BernhardSchuld** [Broadsword-GIS-Org/SE_BroadSword-GIS#37]
Need this function for Access so that they may see what venues (classrooms) are available once they select a building from the list given by #36.

**Comment by Tlaka95** [comment]
@sjohandup  are you doing this one?

**Comment by sjohandup** [comment]
@Tlaka95  yes.  

You can take an issue that hasn't been assigned to anyone and click on assign yourself to the right of the web page 👍

**Comment by sjohandup** [comment]
renamed to getByBuildingName

example use:
localhost:3000/getByBuildingName/IT
