### ISSUE TITLE
DB document structure

### ISSUE THREAD

**Issue by BernhardSchuld** [Broadsword-GIS-Org/SE_BroadSword-GIS#39]
We need to update the DB document structure. 

Fields needed: 
- Location type (stairs, pathway, corridor, building)
- Building
- Room

The latter 2 will be empty or possibly "N/A" if it doesn't apply to the current location

**Comment by sjohandup** [comment]
updated to include location_type
Changed name to room, only under:
module.exports.create;
module.exports.get;
module.exports.getByBuildingName

Other methods will have to be updated in the near future
